# deployments/k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: reference-blog-secrets
  namespace: reference-blog
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION_use_k8s_Secret"
  db-password: "blogpass"
