# deployments/k8s/worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: reference-blog
  labels:
    app: worker
    app.kubernetes.io/part-of: reference-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9093"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: worker
          image: reference-blog/worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9093
              name: metrics
          env:
            - name: DATABASE_DSN
              value: "postgres://bloguser:blogpass@postgres.reference-blog:5432/blog?sslmode=disable"
            - name: KAFKA_BROKERS
              value: "kafka.reference-blog:29092"
            - name: ELASTICSEARCH_ADDRESSES
              value: "http://elasticsearch.reference-blog:9200"
            - name: JAEGER_ENDPOINT
              value: "http://jaeger.reference-blog:14268/api/traces"
            - name: CONSUMER_GROUP
              value: "blog-worker"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
