apiVersion: v1
kind: Service
metadata:
  name: astra-app
  labels:
    app.kubernetes.io/name: astra
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    # Uncomment for gRPC:
    # - port: 9090
    #   targetPort: 9090
    #   protocol: TCP
    #   name: grpc
  selector:
    app.kubernetes.io/name: astra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: astra-app
  labels:
    app.kubernetes.io/name: astra
