// Package graphql provides helpers for mounting GraphQL endpoints on an Astra app.
//
// This package is schema-agnostic: it works with any standard http.Handler,
// whether generated by gqlgen, graphql-go, or another library.
//
// # Quick start with gqlgen
//
//	import (
//	    "github.com/99designs/gqlgen/graphql/handler"
//	    "github.com/astra-go/astra/graphql"
//
//	    "myapp/graph"        // generated package
//	    "myapp/graph/generated"
//	)
//
//	schema := generated.NewExecutableSchema(generated.Config{
//	    Resolvers: &graph.Resolver{},
//	})
//	srv := handler.NewDefaultServer(schema)
//
//	graphql.Mount(app, srv)
//	// Registers:
//	//   POST /graphql     ← query / mutation endpoint
//	//   GET  /graphql     ← introspection (GET with query param)
//	//   GET  /playground  ← GraphQL Playground UI
//
// # Custom paths
//
//	graphql.Mount(app, srv, graphql.Options{
//	    Path:           "/api/graphql",
//	    PlaygroundPath: "/api/graphql/ui",
//	    PlaygroundTitle: "My API",
//	})
//
// # Disabling Playground
//
//	graphql.Mount(app, srv, graphql.Options{PlaygroundPath: ""})
package graphql

import (
	"fmt"
	"net/http"

	"github.com/astra-go/astra"
)

// Options configures the GraphQL endpoint registration.
type Options struct {
	// Path is the URL at which the GraphQL endpoint is mounted.
	// Default: "/graphql"
	Path string

	// PlaygroundPath is the URL at which the interactive GraphQL Playground
	// UI is served. Set to "" to disable the Playground.
	// Default: "/playground"
	PlaygroundPath string

	// PlaygroundTitle is the <title> shown in the Playground.
	// Default: "GraphQL Playground"
	PlaygroundTitle string
}

func (o *Options) setDefaults() {
	if o.Path == "" {
		o.Path = "/graphql"
	}
	if o.PlaygroundPath == "" && o.PlaygroundPath != "" {
		// zero value means disabled only when explicitly set to ""
	}
	if o.PlaygroundTitle == "" {
		o.PlaygroundTitle = "GraphQL Playground"
	}
}

// Mount registers a GraphQL handler on the Astra app.
//
// Both GET and POST requests to opts.Path are forwarded to h. This is the
// standard behaviour expected by GraphQL clients (GET for simple queries /
// introspection, POST for mutations and batched queries).
//
// When opts.PlaygroundPath is non-empty (the default), a lightweight HTML
// Playground page is served at that path for browser-based development and
// exploration.
func Mount(app *astra.App, h http.Handler, opts ...Options) {
	o := Options{}
	if len(opts) > 0 {
		o = opts[0]
	}

	// Apply defaults only for unset fields.
	if o.Path == "" {
		o.Path = "/graphql"
	}
	if o.PlaygroundTitle == "" {
		o.PlaygroundTitle = "GraphQL Playground"
	}
	// PlaygroundPath defaults to "/playground" only when the user did not
	// set Options at all.  An explicit empty string disables the playground.
	playgroundDefault := len(opts) == 0 || (len(opts) > 0 && opts[0].PlaygroundPath == "" && opts[0].Path == "")
	if playgroundDefault {
		o.PlaygroundPath = "/playground"
	}

	adapt := adaptHandler(h)
	app.GET(o.Path, adapt)
	app.POST(o.Path, adapt)

		if o.PlaygroundPath != "" {
			title := o.PlaygroundTitle
			endpoint := o.Path
			app.GET(o.PlaygroundPath, func(c *astra.Ctx) error {
				c.Writer().Header().Set("Content-Type", "text/html; charset=utf-8")
				_, _ = fmt.Fprint(c.Writer(), playgroundHTML(title, endpoint))
				return nil
			})
		}
}

// adaptHandler converts a standard http.Handler into an astra.HandlerFunc.
func adaptHandler(h http.Handler) astra.HandlerFunc {
	return func(c *astra.Ctx) error {
		h.ServeHTTP(c.Writer(), c.Request())
		return nil
	}
}

// playgroundHTML returns a minimal GraphQL Playground HTML page.
// The page loads Playground assets from the official CDN.
func playgroundHTML(title, endpoint string) string {
	return fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>%s</title>
  <meta name="viewport" content="user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/css/index.css" />
  <link rel="shortcut icon" href="https://cdn.jsdelivr.net/npm/graphql-playground-react/build/favicon.png" />
  <script src="https://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js"></script>
</head>
<body>
  <div id="root" />
  <script>
    window.addEventListener('load', function (event) {
      GraphQLPlayground.init(document.getElementById('root'), {
        endpoint: '%s',
        settings: {
          'editor.theme': 'dark',
          'editor.reuseHeaders': true,
          'request.credentials': 'same-origin',
        },
      })
    })
  </script>
</body>
</html>`, title, endpoint)
}
