// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/inventory.proto

package inventorypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_GetStock_FullMethodName      = "/showcase.inventory.v1.InventoryService/GetStock"
	InventoryService_BatchGetStock_FullMethodName = "/showcase.inventory.v1.InventoryService/BatchGetStock"
	InventoryService_DecrStock_FullMethodName     = "/showcase.inventory.v1.InventoryService/DecrStock"
	InventoryService_ListLowStock_FullMethodName  = "/showcase.inventory.v1.InventoryService/ListLowStock"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryService exposes stock management over gRPC.
// All RPCs are tenant-scoped: callers must supply tenant_id.
type InventoryServiceClient interface {
	// GetStock returns the current stock level for a single product.
	GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*StockResponse, error)
	// BatchGetStock returns stock levels for multiple products in one call.
	BatchGetStock(ctx context.Context, in *BatchGetStockRequest, opts ...grpc.CallOption) (*BatchStockResponse, error)
	// DecrStock atomically decrements stock. Returns the updated level.
	// Returns NOT_FOUND if the product does not exist.
	// Returns FAILED_PRECONDITION if stock is insufficient.
	DecrStock(ctx context.Context, in *DecrStockRequest, opts ...grpc.CallOption) (*StockResponse, error)
	// ListLowStock streams products whose stock is at or below the threshold.
	ListLowStock(ctx context.Context, in *ListLowStockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockItem], error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*StockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) BatchGetStock(ctx context.Context, in *BatchGetStockRequest, opts ...grpc.CallOption) (*BatchStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_BatchGetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) DecrStock(ctx context.Context, in *DecrStockRequest, opts ...grpc.CallOption) (*StockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockResponse)
	err := c.cc.Invoke(ctx, InventoryService_DecrStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListLowStock(ctx context.Context, in *ListLowStockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[0], InventoryService_ListLowStock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListLowStockRequest, StockItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_ListLowStockClient = grpc.ServerStreamingClient[StockItem]

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// InventoryService exposes stock management over gRPC.
// All RPCs are tenant-scoped: callers must supply tenant_id.
type InventoryServiceServer interface {
	// GetStock returns the current stock level for a single product.
	GetStock(context.Context, *GetStockRequest) (*StockResponse, error)
	// BatchGetStock returns stock levels for multiple products in one call.
	BatchGetStock(context.Context, *BatchGetStockRequest) (*BatchStockResponse, error)
	// DecrStock atomically decrements stock. Returns the updated level.
	// Returns NOT_FOUND if the product does not exist.
	// Returns FAILED_PRECONDITION if stock is insufficient.
	DecrStock(context.Context, *DecrStockRequest) (*StockResponse, error)
	// ListLowStock streams products whose stock is at or below the threshold.
	ListLowStock(*ListLowStockRequest, grpc.ServerStreamingServer[StockItem]) error
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) GetStock(context.Context, *GetStockRequest) (*StockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedInventoryServiceServer) BatchGetStock(context.Context, *BatchGetStockRequest) (*BatchStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetStock not implemented")
}
func (UnimplementedInventoryServiceServer) DecrStock(context.Context, *DecrStockRequest) (*StockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecrStock not implemented")
}
func (UnimplementedInventoryServiceServer) ListLowStock(*ListLowStockRequest, grpc.ServerStreamingServer[StockItem]) error {
	return status.Error(codes.Unimplemented, "method ListLowStock not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetStock(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_BatchGetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).BatchGetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_BatchGetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).BatchGetStock(ctx, req.(*BatchGetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_DecrStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DecrStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DecrStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DecrStock(ctx, req.(*DecrStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListLowStock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListLowStockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InventoryServiceServer).ListLowStock(m, &grpc.GenericServerStream[ListLowStockRequest, StockItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_ListLowStockServer = grpc.ServerStreamingServer[StockItem]

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "showcase.inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStock",
			Handler:    _InventoryService_GetStock_Handler,
		},
		{
			MethodName: "BatchGetStock",
			Handler:    _InventoryService_BatchGetStock_Handler,
		},
		{
			MethodName: "DecrStock",
			Handler:    _InventoryService_DecrStock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListLowStock",
			Handler:       _InventoryService_ListLowStock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/inventory.proto",
}
