// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetStockRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type BatchGetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProductIds    []uint64               `protobuf:"varint,2,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetStockRequest) Reset() {
	*x = BatchGetStockRequest{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStockRequest) ProtoMessage() {}

func (x *BatchGetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStockRequest.ProtoReflect.Descriptor instead.
func (*BatchGetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *BatchGetStockRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BatchGetStockRequest) GetProductIds() []uint64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type BatchStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockResponse       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStockResponse) Reset() {
	*x = BatchStockResponse{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStockResponse) ProtoMessage() {}

func (x *BatchStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStockResponse.ProtoReflect.Descriptor instead.
func (*BatchStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *BatchStockResponse) GetItems() []*StockResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type DecrStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrStockRequest) Reset() {
	*x = DecrStockRequest{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrStockRequest) ProtoMessage() {}

func (x *DecrStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrStockRequest.ProtoReflect.Descriptor instead.
func (*DecrStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *DecrStockRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *DecrStockRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DecrStockRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type StockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         uint32                 `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockResponse) Reset() {
	*x = StockResponse{}
	mi := &file_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockResponse) ProtoMessage() {}

func (x *StockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockResponse.ProtoReflect.Descriptor instead.
func (*StockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *StockResponse) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StockResponse) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ListLowStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Threshold     uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"` // products with stock <= threshold are returned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLowStockRequest) Reset() {
	*x = ListLowStockRequest{}
	mi := &file_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLowStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLowStockRequest) ProtoMessage() {}

func (x *ListLowStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLowStockRequest.ProtoReflect.Descriptor instead.
func (*ListLowStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ListLowStockRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ListLowStockRequest) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Stock         uint32                 `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *StockItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StockItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StockItem) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\x15showcase.inventory.v1\"M\n" +
	"\x0fGetStockRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\"T\n" +
	"\x14BatchGetStockRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\x04R\n" +
	"productIds\"P\n" +
	"\x12BatchStockResponse\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.showcase.inventory.v1.StockResponseR\x05items\"j\n" +
	"\x10DecrStockRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\"D\n" +
	"\rStockResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\rR\x05stock\"P\n" +
	"\x13ListLowStockRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\rR\tthreshold\"c\n" +
	"\tStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\rR\x05stock2\x91\x03\n" +
	"\x10InventoryService\x12X\n" +
	"\bGetStock\x12&.showcase.inventory.v1.GetStockRequest\x1a$.showcase.inventory.v1.StockResponse\x12g\n" +
	"\rBatchGetStock\x12+.showcase.inventory.v1.BatchGetStockRequest\x1a).showcase.inventory.v1.BatchStockResponse\x12Z\n" +
	"\tDecrStock\x12'.showcase.inventory.v1.DecrStockRequest\x1a$.showcase.inventory.v1.StockResponse\x12^\n" +
	"\fListLowStock\x12*.showcase.inventory.v1.ListLowStockRequest\x1a .showcase.inventory.v1.StockItem0\x01BEZCgithub.com/astra-go/astra/examples/showcase/internal/pb/inventorypbb\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_inventory_proto_goTypes = []any{
	(*GetStockRequest)(nil),      // 0: showcase.inventory.v1.GetStockRequest
	(*BatchGetStockRequest)(nil), // 1: showcase.inventory.v1.BatchGetStockRequest
	(*BatchStockResponse)(nil),   // 2: showcase.inventory.v1.BatchStockResponse
	(*DecrStockRequest)(nil),     // 3: showcase.inventory.v1.DecrStockRequest
	(*StockResponse)(nil),        // 4: showcase.inventory.v1.StockResponse
	(*ListLowStockRequest)(nil),  // 5: showcase.inventory.v1.ListLowStockRequest
	(*StockItem)(nil),            // 6: showcase.inventory.v1.StockItem
}
var file_proto_inventory_proto_depIdxs = []int32{
	4, // 0: showcase.inventory.v1.BatchStockResponse.items:type_name -> showcase.inventory.v1.StockResponse
	0, // 1: showcase.inventory.v1.InventoryService.GetStock:input_type -> showcase.inventory.v1.GetStockRequest
	1, // 2: showcase.inventory.v1.InventoryService.BatchGetStock:input_type -> showcase.inventory.v1.BatchGetStockRequest
	3, // 3: showcase.inventory.v1.InventoryService.DecrStock:input_type -> showcase.inventory.v1.DecrStockRequest
	5, // 4: showcase.inventory.v1.InventoryService.ListLowStock:input_type -> showcase.inventory.v1.ListLowStockRequest
	4, // 5: showcase.inventory.v1.InventoryService.GetStock:output_type -> showcase.inventory.v1.StockResponse
	2, // 6: showcase.inventory.v1.InventoryService.BatchGetStock:output_type -> showcase.inventory.v1.BatchStockResponse
	4, // 7: showcase.inventory.v1.InventoryService.DecrStock:output_type -> showcase.inventory.v1.StockResponse
	6, // 8: showcase.inventory.v1.InventoryService.ListLowStock:output_type -> showcase.inventory.v1.StockItem
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
